apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    labels:
      k8s-app: odl-ovskube-proxy
    name: odl-ovskube-proxy
    namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: odl-ovskube-proxy
  template:
    metadata:
      labels:
        k8s-app: odl-ovskube-proxy
    spec:
      hostNetwork: true
      containers:
        - name: odl-ovskube-proxy
          image: odlkubeproxy:v1.0
          env:
          - name: confFile
            value: "/etc/cni/net.d/odl-cni.conf" # It may need to change based on the deployment env.
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /root/.kube/
            name: kubeconfig
            readOnly: true
          - mountPath: /etc/cni/net.d/
            name: kubeproxy
            readOnly: true
          - mountPath: /var/run/openvswitch/
            name: ovs
            readOnly: false
      volumes:
       - name: kubeconfig
         hostPath:
           path: /home/vagrant/.kube/ # This directory needs to change based on the deployement
       - name: ovs
         hostPath:
           path: /var/run/openvswitch/
       - name: kubeproxy
         hostPath:
           path: /etc/cni/net.d/