---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: odlwatcher
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odlwatcher
  namespace: kube-system
rules:
- apiGroups: ["*"] 
  resources: ["*"]
  verbs: ["*"]


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odlwatcher
  namespace: kube-system
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: odlwatcher
roleRef:
  kind: ClusterRole
  name: odlwatcher
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1 
kind: DaemonSet
metadata:
  name: odlwatcher
  namespace: kube-system
spec:
  selector:
      matchLabels:
        name: odlwatcher # Label selector that determines which Pods belong to the DaemonSet
  template:
    metadata:
      labels:
        name: odlwatcher # Pod template's label selector
    spec: 
      containers:
      - name: odlwatcher
        args: ["odl"]
        image: odlwatcher
        imagePullPolicy: Never
      hostNetwork: true
      serviceAccountName: odlwatcher
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"

