apiVersion: v1
kind: Service
metadata:
  labels:
    name: websvc
    role: service
  name: websvc
spec:
  ports:
    - port: 8800
      targetPort: 80
      protocol: TCP
      name: tcp
  selector:
    name: webserver
